# Generated by Django 2.2.6 on 2019-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=20)),
                ('UrlAdresse', models.CharField(max_length=255)),
                ('Benutzername', models.CharField(max_length=15)),
                ('Passwort', models.CharField(max_length=30)),
                ('Benutzerdefiniert', models.BooleanField()),
                ('Hours', models.IntegerField()),
                ('Hours2', models.IntegerField()),
                ('Minutes', models.IntegerField()),
                ('Minutes2', models.IntegerField()),
                ('FehlschlagAlert', models.BooleanField()),
                ('ErfolgNachFehlschlagAlert', models.BooleanField()),
                ('ZuVielFehlschlaege', models.BooleanField()),
                ('AntwortenSpeichern', models.BooleanField()),
                ('MyNumber', models.IntegerField()),
                ('MyNumber2', models.IntegerField()),
            ],
        ),
    ]
